Разбивка компонента «Конструктор пиццы» на мелкие компоненты
htmlacademy-vue/592167-pizza-1 pull request #2
Opened 2022-02-04 11:06 UTC by Agafon87

2022-02-05 02:27 UTC, enotke requested changes

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/common/components/AppDrag.vue
> +    <slot></slot>
Нужно закрывать все теги, компоненты, слоты в которых нет содержимого.
https://up.htmlacademy.ru/vue/1/criteries#b14

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/common/components/AppDrag.vue
> +    <slot></slot>
Можешь настроить Eslint в своем IDE и добавить плагин vue/html-self-closing

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientPicture.vue
> +    ingredient: Object,
Не хорошо передавать объекты в props.
Вот смотри, в этом компоненте используется только name и rusName. Их и нужно передавать. Так будет легче отслеживать ошибки и будет возможность проверять типы данных которые приходят в компонент. Ну и в дальнейшем при большом количестве разных компонентов тебе будет проще понять что конкретно нужно тому или иному компоненту.

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              v-model="sauceInfo"
v-model обеспечивает двунаправленное связывание данных. Это означает, что v-model может изменить значение sauceInfo, а sauceInfo это props который передается в компонент по значению и доступен только для чтения

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              v-model="sauceInfo"
Если тебе нужно изменять значения только через кнопки + и -, то эта директива тут вообще не нужна, но если ты хочешь сделать так, чтобы пользователь сам мог вводить значение в поле ввода, то нужно самому обрабатывать событие change аналогично кнопкам + и -

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                :idx="idx"
Не нужно использовать ключи массива в качестве ID для ингредиента, тк у них есть свои ID и они будут отличаться от ключей массива

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      const ingredient = this.ingredients.find((it) => it.id === idx + 1);
Вот из за того, что ты используешь ключи массива тебе приходится увеличивать значение на единицу.

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      direction === "increment" ? ingredient.count++ : ingredient.count--;
И тут можно сделать гораздо проще. Вместо того, чтобы передавать действие и элемент можно в самом компоненте app-item-counter передавать уже итоговое значение и тут просто его присваивать. Например. Ты передаешь параметры: ingredientCount и ingredientId, и при изменении значения в поле ввода или при клике по кнопкам + и - вызываешь событие $emit('update:ingredientCount', newValue) где newValue это уже нужное количество ингредиентов

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +  name: "BuilderSizeSelector",
В этом компоненте необходимо добавить обработчики событий для изменения размера пиццы. Сейчас этот функционал не работает

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    getIngredientClassName(name) {
Этот метод не используется

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +            v-model="doughSize"
Тут тоже самое, нельзя изменять то, что передается в props. Нужно вызывать событие для обновления размера

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    <p>Итого: 0 ₽</p>
Нужно передавать итоговую сумму в компонент

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +            :value="getPizzaDiameterClassName(size.name)"
Проблемы с наименованием. Советую четко разделить то что ты выводишь пользователю и то что нужно для внутренней реализации выбора размера пиццы. 
23 см - это название размера пиццы для пользователя
small - это название типа размера пиццы для внутренней реализации.

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +            :value="getPizzaDiameterClassName(size.name)"
Можно переименовать 
23 см в name, а small в slug. Тогда будет понятно что и для чего нужно. А то ты передаешь в качестве значения инпута diametrClassName

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +import AppDrop from "../../../common/components/AppDrop";
При импорте нужно использовать alias. Это позволит потом спокойно переносить компоненты из одной папки в другую при этом не меняя импорты.
Пример:
`import AppDrop from "@/common/components/AppDrop";`
Опять же, если настроить IDE, то всё это будет импортироваться автоматически

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/common/components/AppItemCounter.vue
> +      return this.ingredientCount >= 3;
Такие вещи, как например максимальное количество выбранных элементов, нужно выносить в константы и использовать эту константу во всех необходимых местах. Это позволит понять, где ещё используется этот лимит и при необходимости легко его поменять изменив всего одну константу

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      direction === "increment" ? ingredient.count++ : ingredient.count--;
Не смог найти тебя в slack. Если что-то непонятно можешь написать мне в том же slack или в Telegram.
Telegram Id: `@Enotke`

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/views/Index.vue
> +          count: 0,
Советую отделять статические и динамические данные. 
Нужно делать что-то в таком духе.
ingredientsList - список доступных ингредиентов
selectedIngredients - список ингредиентов которые выбрал пользователь.
И далее все изменения будут затрагивать только selectedIngredients. 
Можешь подумать над тем, какая  у selectedIngredients может быть структура.
Например можно сделать объект в котором будут выбранные элементы. В этом объекте в качестве ключа будут названия ингредиентов (или их идентификатор), а в качестве значения - количество этих ингредиентов

2022-02-05 02:27 UTC, enotke commented on src/frontend/src/layouts/AppLayout.vue
> +      <a href="#">0 ₽</a>
Сюда также нужно передавать итоговую стоимость заказа

2022-02-08 12:22 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderIngredientPicture.vue
> +    ingredient: Object,
Поменял

2022-02-08 12:34 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              v-model="sauceInfo"
Так это же не добавление ингредиентов, которое мы делаем через кнопки "+" и "-", это выбор соуса: радио-кнопки и по этому я тут использовал v-model. Просто мне непонятно пока, а что вместо них тут использовать?

2022-02-08 12:47 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                :idx="idx"
Поправил

2022-02-08 12:47 UTC, Agafon87 commented on src/frontend/src/views/Index.vue
> +      const ingredient = this.ingredients.find((it) => it.id === idx + 1);
Поправил

2022-02-08 17:17 UTC, Agafon87 commented on src/frontend/src/views/Index.vue
> +      direction === "increment" ? ingredient.count++ : ingredient.count--;
Но мы же не сможем просто передать значение, нам как минимум нужно ещё передать и id элемента, которому мы потом будем менять это значение. Мы же на этом этапе не используем Vuex или provide/inject. А так мысль уловил, согласен.

2022-02-08 17:45 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +  name: "BuilderSizeSelector",
Добавил

2022-02-08 17:46 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    getIngredientClassName(name) {
Удалил

2022-02-08 17:52 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +            v-model="doughSize"
Убрал v-model

2022-02-09 15:23 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    <p>Итого: 0 ₽</p>
Добавил подсчет итоговой суммы

2022-02-09 15:32 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +            :value="getPizzaDiameterClassName(size.name)"
Не понял, где и как надо переименовать.

2022-02-09 15:37 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +import AppDrop from "../../../common/components/AppDrop";
Переделал на alias

2022-02-10 17:20 UTC, Agafon87 commented on src/frontend/src/common/components/AppItemCounter.vue
> +      return this.ingredientCount >= 3;
Добавил константы.

2022-02-10 17:23 UTC, Agafon87 commented on src/frontend/src/layouts/AppLayout.vue
> +      <a href="#">0 ₽</a>
Добавил вывод итоговой суммы.

2022-02-10 17:25 UTC, Agafon87 commented on src/frontend/src/views/Index.vue
> +          count: 0,
Это лучше обсудить на консультации.

2022-02-11 00:01 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              v-model="sauceInfo"
Проблема в том, что нельзя менять значения входных параметров (props)

2022-02-14 15:01 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +            :value="getPizzaDiameterClassName(size.name)"
Добавил переменную slug

2022-02-17 22:01 UTC, enotke approved these changes

2022-02-17 22:01 UTC, merged