Подключение Vuex.
htmlacademy-vue/592167-pizza-1 pull request #4
Opened 2022-03-15 07:04 UTC by Agafon87

2022-03-15 22:26 UTC, enotke requested changes

2022-03-15 22:26 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      this.count = keysNames.includes(active)
Это можно хранить и в локальной переменной

2022-03-15 22:26 UTC, enotke commented on src/frontend/src/store/modules/builder.store.js
> +      state = { ...state, data };
Так не будет работать. Нужно менять параметры в стейте, я не перезаписывать его

2022-03-15 22:26 UTC, enotke commented on src/frontend/src/views/Index.vue
>        isAuth: true,
Не используется

2022-03-15 22:39 UTC, enotke requested changes

2022-03-15 22:39 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
>                  @changeCount="changeCount"
Лишнее

2022-03-21 05:26 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
>                  @changeCount="changeCount"
Не понял, почему лишнее? Ведь классы меняются у разных div-ов.

2022-03-21 05:29 UTC, Agafon87 commented on src/frontend/src/views/Index.vue
>        isAuth: true,
Удалил.

2022-03-21 05:31 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      this.count = keysNames.includes(active)
Не понял, что конкретно хранить в переменной нужно.

2022-03-21 05:39 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
>                  @changeCount="changeCount"
Я про changeCount

2022-03-21 05:42 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      this.count = keysNames.includes(active)
this.count. Он не нужен в data, тк ты его только в в одном методе используешь

2022-03-21 05:46 UTC, Agafon87 commented on src/frontend/src/store/modules/builder.store.js
> +      state = { ...state, data };
Переделал.

2022-03-21 06:14 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +      this.count = keysNames.includes(active)
Переделал.

2022-03-21 06:14 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
>                  @changeCount="changeCount"
Переделал.

2022-03-21 11:35 UTC, merged