module5-task1
htmlacademy-vue/592167-pizza-1 pull request #5
Opened 2022-04-15 09:13 UTC by Agafon87

2022-04-15 10:37 UTC, enotke requested changes

2022-04-15 10:37 UTC, enotke commented on src/frontend/src/common/mixins/validator.js
> +    rule: (value) => !!value?.trim(),
А в чем разница между required и isNotEmpty?

2022-04-15 10:37 UTC, enotke commented on src/frontend/src/store/modules/auth.store.js
> +      const data = await this.$api.auth.login(credentials);
Нужно обрабатывать ошибки

2022-04-15 10:37 UTC, enotke commented on src/frontend/src/store/modules/auth.store.js
> +      this.$jwt.saveToken(data.token);
В случае ошибки токен не передается

2022-04-15 10:37 UTC, enotke commented on src/frontend/src/views/Cart.vue
> +    <app-popup v-if="isOpenPopup" @closePopup="onClosePopupClick"></app-popup>
<app-popup v-if="isOpenPopup" @closePopup="onClosePopupClick"/>

2022-04-15 10:37 UTC, enotke commented on src/frontend/src/store/modules/orders.store.js
> +      return "";
Можно ничего не возвращать

2022-04-15 10:37 UTC, enotke commented on src/frontend/src/services/api.service.js
> +  constructor(resource, notifier) {
Каждый класс принято писать в отдельном файле

2022-04-15 10:37 UTC, enotke commented on src/frontend/src/views/Cart.vue
> +      if (this.$refs.cartMain.$refs.cartForm.validationFields()) {
Для чего ref? Лучше уж через слот передавать нужные методы

2022-04-18 05:32 UTC, Agafon87 commented on src/frontend/src/common/mixins/validator.js
> +    rule: (value) => !!value?.trim(),
Это было дано в учебном проекте. Я так думаю, что это показали чисто для ознакомления. Так как разницы между ними я тоже не понял.

2022-04-18 05:35 UTC, Agafon87 commented
Через ref я добираюсь до метода потомка из родителя. А метод в потомка передавать через slot или через props?

2022-04-18 05:36 UTC, Agafon87 commented on src/frontend/src/services/api.service.js
> +  constructor(resource, notifier) {
Тоже делал по образу и подобию учебного проекта.

2022-04-18 05:37 UTC, Agafon87 commented on src/frontend/src/views/Cart.vue
> +    <app-popup v-if="isOpenPopup" @closePopup="onClosePopupClick"></app-popup>
Поправил

2022-04-18 05:38 UTC, Agafon87 commented on src/frontend/src/store/modules/orders.store.js
> +      return "";
Поправил

2022-04-18 23:10 UTC, enotke commented
@Agafon87 Тут же не получится через props сделать тк компоненты находятся на одном уровне. Ну вообще сделать то можно, но нужно будет либо слишком костыльно, либо придется много переделывать

2022-04-20 05:58 UTC, Agafon87 commented on src/frontend/src/common/mixins/validator.js
> +    rule: (value) => !!value?.trim(),
Удалил метод isNotEmpty

2022-04-20 05:59 UTC, Agafon87 commented on src/frontend/src/services/api.service.js
> +  constructor(resource, notifier) {
Вынес классы в отдельные файлы

2022-04-21 21:13 UTC, merged

2022-04-22 07:46 UTC, enotke commented on src/frontend/src/services/api_classes/crud-api-service.js
> +  constructor(resource, notifier) {
BaseApiService в конструкторе принимает только один параметр

2022-04-22 07:46 UTC, enotke commented on src/frontend/src/modules/cart/CartMain.vue
> +        <slot name="cartForm"></slot>
`<slot name="cartForm" />`

2022-04-22 07:46 UTC, enotke commented on src/frontend/src/common/components/AppItemCounter.vue
> +    ingredient: {
Лучше тогда вообще не передавать ничего. А в родительском классе обрабатывать вот так `@changeIngredientCount="changeCount($event, ingredient.id)`

2022-04-22 07:46 UTC, enotke commented on src/frontend/src/store/modules/cart.store.js
> +      const pizza = state.pizzas.find((it) => it.pizzaName === data.name);
Лучше присваивать пиццам какой-нибудь id при добавлении в корзину. А то получается, что можно удалить другую пиццу с одинаковым названием

2022-04-22 07:46 UTC, enotke commented on src/frontend/src/common/helpers.js
> +  return pizzas.map((_, idx) => ({
`  return pizzas.map((item) => ({
    name: item.pizzaName,
    sauceId: item.sauceId,
    doughId: item.doughId,
    sizeId: item.pizzaSizeId,
    quantity: item.quantity,
    ingredients: item.selectedIngredients,
  }));`

2022-04-22 08:20 UTC, Agafon87 commented on src/frontend/src/services/api_classes/crud-api-service.js
> +  constructor(resource, notifier) {
Поправил.

2022-04-22 08:22 UTC, Agafon87 commented on src/frontend/src/modules/cart/CartMain.vue
> +        <slot name="cartForm"></slot>
Поправил.

2022-04-22 10:18 UTC, Agafon87 commented on src/frontend/src/common/components/AppItemCounter.vue
> +    ingredient: {
Поравил

2022-04-22 10:43 UTC, Agafon87 commented on src/frontend/src/common/helpers.js
> +  return pizzas.map((_, idx) => ({
Поправил

2022-04-22 10:59 UTC, Agafon87 commented on src/frontend/src/store/modules/cart.store.js
> +      const pizza = state.pizzas.find((it) => it.pizzaName === data.name);
Надо подумать.