module7-task1
htmlacademy-vue/592167-pizza-1 pull request #7
Opened 2022-05-12 11:59 UTC by Agafon87

2022-05-12 22:28 UTC, enotke requested changes

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/common/__tests__/helpers.spec.js
> +    const pizzaSizeId = pizza.sizes[1].id;
Не нужно использовать static/pizza. Тесты должны быть максимально простыми и прозрачными

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/common/components/__tests__/AppButtonCounter.spec.js
> +    wrapper.vm.$emit("changeCount");
Странный тест. Ты кидаешь событие и сам же его проверяешь. Тут тебе нужно найти кнопку `wrapper.find(".counter__button")` и кликнуть по ней

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/common/components/__tests__/AppButtonCounter.spec.js
> +    expect(button.attributes("disabled")).toBeFalsy();
Почему тогда тест называется button must be disabled?

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/common/components/__tests__/AppInput.spec.js
> +    createComponent({ localVue, propsData, computed });
А смысл передавать computed и проверять его? Тут нужно передавать пропс errorText и проверять, блок `text-field__text--error` не отображается

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/common/components/__tests__/AppInput.spec.js
> +    wrapper.vm.$emit("input");
Опять же. Нужно изменить текст в инпуте и потом проверять событие

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/modules/builder/components/__tests__/BuilderPizzaView.spec.js
> +    store.state["Builder"].ingredients = pizza.ingredients;
В тестах принято хардкодить передаваемые значения. Получается, что если что-то поменяется в pizza.json, то это сломает тест, а так быть не должно. Передавай в store.state["Builder"].ingredients какой-то минимум, необходимый для работы теста.

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/views/__tests__/Cart.spec.js
> +    expect(errorMessage.element.textContent).toBe(
Можно использовать метод errorMessage.text()

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/views/__tests__/Login.spec.js
> +  });
Ещё можно проверить успешную отправку формы

2022-05-12 22:28 UTC, enotke commented on src/frontend/src/views/__tests__/Orders.spec.js
> +    const mockMethodRepeat = jest.spyOn(wrapper.vm, "onRepeatOrderClick");
По хорошему бы конечно проверять не сам факт вызова мутации, а изменение состояния

2022-05-12 22:29 UTC, enotke commented
Ещё нужно сделать тесты для AppDrag/Drop

2022-05-12 22:32 UTC, enotke requested changes

2022-05-12 22:32 UTC, enotke commented on src/frontend/src/views/__tests__/Index.spec.js
> +import Index from "@/views";
Ошибка в импорте

2022-05-13 05:42 UTC, Agafon87 commented on src/frontend/src/views/__tests__/Index.spec.js
> +import Index from "@/views";
Поправил

2022-05-13 05:46 UTC, Agafon87 commented on src/frontend/src/views/__tests__/Cart.spec.js
> +    expect(errorMessage.element.textContent).toBe(
Поправил.

2022-05-13 07:07 UTC, Agafon87 commented on src/frontend/src/common/__tests__/helpers.spec.js
> +    const pizzaSizeId = pizza.sizes[1].id;
Поправил.

2022-05-13 07:30 UTC, Agafon87 commented on src/frontend/src/common/components/__tests__/AppButtonCounter.spec.js
> +    wrapper.vm.$emit("changeCount");
Поправил.

2022-05-13 07:34 UTC, Agafon87 commented on src/frontend/src/common/components/__tests__/AppButtonCounter.spec.js
> +    expect(button.attributes("disabled")).toBeFalsy();
Поправил.

2022-05-13 07:58 UTC, Agafon87 commented on src/frontend/src/common/components/__tests__/AppInput.spec.js
> +    createComponent({ localVue, propsData, computed });
Поправил.

2022-05-13 07:59 UTC, Agafon87 commented on src/frontend/src/common/components/__tests__/AppInput.spec.js
> +    wrapper.vm.$emit("input");
Поправил.

2022-05-13 09:54 UTC, Agafon87 commented on src/frontend/src/modules/builder/components/__tests__/BuilderPizzaView.spec.js
> +    store.state["Builder"].ingredients = pizza.ingredients;
Поправил.

2022-05-13 11:40 UTC, Agafon87 commented on src/frontend/src/views/__tests__/Login.spec.js
> +  });
Добавил проверку вызова метода loginUser

2022-05-13 12:26 UTC, Agafon87 commented on src/frontend/src/views/__tests__/Orders.spec.js
> +    const mockMethodRepeat = jest.spyOn(wrapper.vm, "onRepeatOrderClick");
Добавил проверку состояния стора корзины.

2022-05-16 11:07 UTC, merged